#!/bin/bash
# Script para controlar todas as VM online
# Thiago Melo <thiago(at)oxente.org>
#

comando=cmd
x_vms=runningvms
x_cmd=controlvm

if [[ $# -eq 0 ]] ; then
    echo "Forma de uso: ${0##*/} [ pause|resume|reset|poweroff|savestate|status ]"
    exit 0
fi

case "$1" in
    status) VBoxManage list vms --long | grep -e "Name:" -e "State:" 
	    ;;
    pause|resume|reset|poweroff|savestate) comando=$1 ;;
esac

if [[ $comando = 'resume' ]] ; then x_vms=vms;x_cmd=startvm;comando='--type headless'; fi


if  [[ ! $comando = 'cmd' ]] ; then 
	echo "Executnado o comando $comando nas VMs"
	for vm in $(VBoxManage list ${x_vms} | awk '{print substr($2, 2, length($2) - 2)}') 
	do
		vmname=`VBoxManage showvminfo ${vm} | grep Name: | awk '{print $2}'`
		echo "VM: ${vmname}"
		VBoxManage ${x_cmd} ${vm} $comando 
		echo "VM ${vm} esta $comando"
	done
fi	
