#!/bin/bash
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
< /dev/urandom tr -dc '_A-Z-a-z-0-9-!@#$%^&*()_+{}|:?=' | head -c${1:-18};echo;
