#!/bin/bash
CUR_DIR=$(pwd)

echo -e "\n\033[1mPulling in latest changes for all repositories...\033[0m\n"

# Find all git repositories and update it to the master latest revision
for i in $(find . -name ".git" | cut -c 3-); do
    echo "";
    echo -e "\033[33m"+$i+"\033[0m";
    cd "$i";
    cd ..;
    #git pull origin master;
    git pull;

    cd $CUR_DIR

done

echo -e "\n\033[32mComplete!\033[0m\n"
