#!/bin/bash

# Number of pings to execute
ping_count=2

# List of regions to ping
regions=(us-east-1
us-east-2
us-gov-west-1
us-west-1
us-west-2
ap-northeast-1
ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
ca-central-1
cn-north-1
cn-northwest-1
eu-central-1
eu-west-1
eu-west-2
eu-west-3
sa-east-1)

for region in ${regions[@]}; do
    printf "$region:\t"
    if [ "${region:0:2}" == "cn" ]; then
        ping -c $ping_count ec2.$region.amazonaws.com.cn |\
            tail -1 | awk '{print $4}' | cut -d '/' -f 2
    else
        ping -c $ping_count ec2.$region.amazonaws.com |\
            tail -1 | awk '{print $4}' | cut -d '/' -f 2
    fi
done


