#!/bin/bash
printf "%-10s%-15s%-15s%-15s%s\n" "PID" "OWNER" "MEMORY" "MB" "COMMAND"

function ps_mem() {
	PSMEM=$(ps -o pid,user,%mem,command ax | grep -v PID | awk '/[0-9]*/{print $1 ":" $2 ":" $4}')


	for z in $PSMEM
	do
		PID=$(echo $z | cut -d: -f1)
		OWN=$(echo $z | cut -d: -f2)
		COM=$(echo $z | cut -d: -f3)
		MEM=$(sudo pmap $PID | tail -n 1 | awk '/[0-9]K/{print $2}')
		MMB=$(($(echo $MEM| sed -e 's/K//g')/1024))MB

		printf "%-10s%-15s%-15s%-15s%s\n" "$PID" "$OWN" "$MEM" "$MMB" "$COM"
	done
}

ps_mem | sort -bnr -k3
